defaultSourceData: "file"           # for import of data
# file types that are allowed for import from Pandora ("ckan")
ckanFileTypes:
  - "xls"
  - "xlsx"
  - "csv"
  - "odt"
  - "txt"
ckanModelTypes:
  - "zip"
  - "resources"
githubRepo: "resources"        # for import of models
defaultSourceModel: "file"           # for import of models
fileExtension: "resources"      # for download of models
rPackageName: "ReSources"       # for download and import of models
# default range of axis for ggplots
plotRange:
  min: 0
  max: 1
  fromData: true
# default values for plot titles
plotTitle:
  text: ""
  fontType: "plain"
  color: "#000000"
  size: 24
  hide: false
plotText:
  fontType: "plain"
  color: "#000000"
  size: 18
  hide: false
# default format of graph and axis titles (for plotExport.R)
availableElements:
  title:
    plot title: "plotTitle"
  axis:
    x axis title: "xAxisTitle"
    x axis text: "xAxisText"
    y axis title: "yAxisTitle"
    y axis text: "yAxisText"
  legend:
    legend title: "legendTitle"
    legend text: "legendText"
