defaultSourceData: "file"           # for import of data
defaultSourceModel: "file"           # for import of models
fileExtension: "resources"      # for download of models
rPackageName: "ReSources"       # for download and import of models
